<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

    $config['use_page_numbers'] = TRUE;
    $config['full_tag_open'] = '<div class="clearfix"><ul class="pagination">';
    $config['full_tag_close'] = '</ul></div>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><span>';
    $config['cur_tag_close'] = '</span></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['prev_link'] = '<i class="fa fa-angle-left"></i>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';
    $config['next_link'] = '<i class="fa fa-angle-right"></i>';
    $config['first_link'] = '<i class="fa fa-angle-double-left"></i>';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_link'] = '<i class="fa fa-angle-double-right"></i>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';