/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artists/{artistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artist details by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the artist to retrieve */
                    artistId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Artist details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: components["schemas"]["Artist"]["id"];
                            name?: components["schemas"]["Artist"]["name"];
                            type?: components["schemas"]["Artist"]["type"];
                        };
                    };
                };
                /** @description Artist not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: "Artist not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{artistId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entries associated with an artist */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination */
                    page?: number;
                };
                header?: never;
                path: {
                    /** @description ID of the artist */
                    artistId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of entries for the artist with pagination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries?: (components["schemas"]["Entry"] & {
                                verses?: {
                                    text?: components["schemas"]["Verse"]["text"];
                                    isMain?: components["schemas"]["Verse"]["isMain"];
                                    isOriginal?: components["schemas"]["Verse"]["isOriginal"];
                                    language?: components["schemas"]["Verse"]["language"];
                                }[];
                                tags?: {
                                    name?: components["schemas"]["Tag"]["name"];
                                    slug?: components["schemas"]["Tag"]["slug"];
                                    color?: components["schemas"]["Tag"]["color"];
                                }[];
                                pulses?: {
                                    creationDate?: components["schemas"]["Pulse"]["creationDate"];
                                }[];
                            })[];
                            /** @description Current page number */
                            page?: number;
                            /** @description Total number of pages */
                            totalPages?: number;
                            artist?: {
                                id?: components["schemas"]["Artist"]["id"];
                                name?: components["schemas"]["Artist"]["name"];
                                type?: components["schemas"]["Artist"]["type"];
                            };
                        };
                    };
                };
                /** @description Artist not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: "Artist not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of entries */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination (1-indexed) */
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A paginated list of entries with verses, tags, and pulses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries?: (components["schemas"]["Entry"] & {
                                verses?: components["schemas"]["Verse"][];
                                tags?: components["schemas"]["Tag"][];
                                pulses?: components["schemas"]["Pulse"][];
                            })[];
                            /** @description Total number of entries */
                            count?: number;
                            /** @description Total number of pages */
                            totalPages?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single entry by ID with full details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the entry to retrieve */
                    entryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entry with verses, tags, songs, and pulses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entry"] & {
                            verses?: components["schemas"]["Verse"][];
                            tags?: components["schemas"]["Tag"][];
                            pulses?: components["schemas"]["Pulse"][];
                            songs?: {
                                id?: components["schemas"]["Song"]["id"];
                                name?: components["schemas"]["Song"]["name"];
                                coverUrl?: components["schemas"]["Song"]["coverUrl"];
                                /** @description Video URL from PV */
                                videoUrl?: string | null;
                                artists?: (components["schemas"]["Artist"] & {
                                    ArtistOfSong?: components["schemas"]["ArtistOfSong"];
                                })[];
                            }[];
                        };
                    };
                };
                /** @description Entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            message?: "Entry not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/screensaver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get randomized verses and entries for screensaver display */
        get: {
            parameters: {
                query?: {
                    /** @description Filter verses by type (original language or main display verse) */
                    type?: "original" | "main";
                    /**
                     * @description Comma-separated list of language codes to filter verses by
                     * @example ja,en,zh
                     */
                    languages?: string;
                    /**
                     * @description Comma-separated list of tag slugs to filter entries by
                     * @example core,light,soft
                     */
                    tags?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Randomized verses and their associated entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Map of entry IDs to entry objects */
                            entries?: {
                                [key: string]: {
                                    id?: components["schemas"]["Entry"]["id"];
                                    title?: components["schemas"]["Entry"]["title"];
                                    producersName?: components["schemas"]["Entry"]["producersName"];
                                    vocalistsName?: components["schemas"]["Entry"]["vocalistsName"];
                                    tags?: {
                                        name?: components["schemas"]["Tag"]["name"];
                                        slug?: components["schemas"]["Tag"]["slug"];
                                        color?: components["schemas"]["Tag"]["color"];
                                    }[];
                                };
                            };
                            /** @description Shuffled array of verses matching the filter criteria */
                            verses?: {
                                id?: components["schemas"]["Verse"]["id"];
                                text?: components["schemas"]["Verse"]["text"];
                                typingSequence?: components["schemas"]["Verse"]["typingSequence"];
                                language?: components["schemas"]["Verse"]["language"];
                                entryId?: components["schemas"]["Verse"]["entryId"];
                            }[];
                        };
                    };
                };
                /** @description No entries found matching the filter criteria */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            message?: "No entries found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bump/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bump an entry with a pulse */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully bumped the entry. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @description The creation date of the new pulse.
                             */
                            creationDate?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Entry not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            message?: "Entry not found";
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search entries */
        get: {
            parameters: {
                query: {
                    /** @description Search query */
                    query: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of entries matching the search query */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Entry"] & {
                            verses?: components["schemas"]["Verse"][];
                            tags?: components["schemas"]["Tag"][];
                            pulses?: components["schemas"]["Pulse"][];
                        })[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a random verse */
        get: {
            parameters: {
                query?: {
                    /** @description Type of verse to filter by (original or main) */
                    type?: "original" | "main";
                    /** @description Comma-separated list of language codes to filter by */
                    languages?: string;
                    /** @description Comma-separated list of tag slugs to filter by */
                    tags?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A random verse matching the specified criteria */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Verse"] & {
                            entry?: components["schemas"]["Entry"] & {
                                tags?: components["schemas"]["Tag"][];
                            };
                        };
                    };
                };
                /** @description No verse found matching the criteria */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            message?: "No verse found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versesBySong": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verses by song ID */
        get: {
            parameters: {
                query: {
                    /** @description ID of the song to get verses for */
                    songId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of entries associated with the specified song */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Entry"] & {
                            verses?: components["schemas"]["Verse"][];
                            tags?: components["schemas"]["Tag"][];
                            pulses?: components["schemas"]["Pulse"][];
                        })[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/og/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Open Graph image for an entry */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the entry to generate Open Graph image for */
                    entryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open Graph image in PNG format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": unknown;
                    };
                };
                /** @description Entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 123 is not found. */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan music files directory and sync with database
         * @description Scans the music files directory, adds new files, updates existing ones, and removes records for deleted files
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scan completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                            data?: {
                                /**
                                 * @description Number of new files added to database
                                 * @example 5
                                 */
                                added?: number;
                                /**
                                 * @description Number of database records removed
                                 * @example 2
                                 */
                                deleted?: number;
                                /**
                                 * @description Number of files with updated metadata
                                 * @example 3
                                 */
                                updated?: number;
                                /**
                                 * @description Number of files without changes
                                 * @example 100
                                 */
                                unchanged?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all music files */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all music files */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MusicFile"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a music file by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Music file details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MusicFile"];
                    };
                };
                /** @description Music file not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update music file metadata
         * @description Updates metadata for a music file and writes changes to the physical file
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        songId?: components["schemas"]["MusicFile"]["songId"];
                        albumId?: components["schemas"]["MusicFile"]["albumId"];
                        trackName?: components["schemas"]["MusicFile"]["trackName"];
                        trackSortOrder?: components["schemas"]["MusicFile"]["trackSortOrder"];
                        albumName?: components["schemas"]["MusicFile"]["albumName"];
                        albumSortOrder?: components["schemas"]["MusicFile"]["albumSortOrder"];
                        artistName?: components["schemas"]["MusicFile"]["artistName"];
                        artistSortOrder?: components["schemas"]["MusicFile"]["artistSortOrder"];
                    };
                };
            };
            responses: {
                /** @description Updated music file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MusicFile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Music file not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Not found";
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/files/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download music file
         * @description Streams the actual music file (audio file)
         */
        get: {
            parameters: {
                query?: {
                    /** @description If present, triggers download with Content-Disposition header */
                    download?: boolean;
                };
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The music file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mpeg": unknown;
                        "audio/flac": unknown;
                        "audio/aiff": unknown;
                    };
                };
                /** @description Music file entry or physical file not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: 404;
                            /** @enum {string} */
                            message?: "Entry not found" | "File not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/lrc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download LRC lyrics file
         * @description Retrieves the LRC lyrics file associated with the music file
         */
        get: {
            parameters: {
                query?: {
                    /** @description If present, triggers download with Content-Disposition header */
                    download?: boolean;
                };
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The LRC lyrics file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/lrc": unknown;
                    };
                };
                /** @description Music file entry or lyrics file not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: 404;
                            /** @enum {string} */
                            message?: "Entry not found" | "File not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/lrcx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download LRCX lyrics file
         * @description Retrieves the LRCX lyrics file associated with the music file
         */
        get: {
            parameters: {
                query?: {
                    /** @description If present, triggers download with Content-Disposition header */
                    download?: boolean;
                };
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The LRCX lyrics file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/lrcx": unknown;
                    };
                };
                /** @description Music file entry or lyrics file not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: 404;
                            /** @enum {string} */
                            message?: "Entry not found" | "File not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cover art for music file
         * @description Extracts and returns the embedded cover art from the music file
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cover art image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": unknown;
                    };
                };
                /** @description Music file not found or has no cover art */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: 404;
                            /** @enum {string} */
                            message?: "Music file entry not found." | "Music file has no cover (via database)." | "Music file has no cover (via file).";
                        };
                    };
                };
                /** @description Error extracting cover art */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: 500;
                            /** @description Error message */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Upload cover art for music file
         * @description Uploads and embeds cover art into a music file from either a file upload or a remote URL
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the music file */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        cover: string;
                    } | {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Cover art uploaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 200;
                            message: "Done.";
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Music file entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Music file entry not found.";
                        };
                    };
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 415 */
                            status?: number;
                            /** @example image/svg+xml is not an acceptable MIME type. */
                            message?: string;
                        };
                    };
                };
                /** @description Neither cover nor url was provided */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 422;
                            message: "Either `cover` or `url` must be provided.";
                        };
                    };
                };
                /** @description Error saving cover art to file */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 500 */
                            status?: number;
                            /** @example Error saving cover art to file */
                            message?: string;
                        };
                    };
                };
                /** @description Error downloading cover from remote URL */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 504 */
                            status?: number;
                            /** @example Request to download the cover has returned a 404 error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/playlists/{slug}.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate an M3U8 playlist file
         * @description Retrieves a playlist by its slug and generates an M3U8 format playlist file containing the music files in the playlist
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The slug identifier of the playlist
                     * @example core
                     */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description M3U8 playlist file */
                200: {
                    headers: {
                        /** @description Suggests the browser to download the file with the playlist slug as filename */
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mpegurl": string;
                    };
                };
                /** @description Playlist not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Playlist not found.";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{songId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a song by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the song to retrieve */
                    songId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Song details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Song"] & {
                            artists?: (components["schemas"]["Artist"] & {
                                ArtistOfSong?: components["schemas"]["ArtistOfSong"];
                            })[];
                            albums?: (components["schemas"]["Album"] & {
                                SongInAlbum?: components["schemas"]["SongInAlbum"];
                            })[];
                            files?: components["schemas"]["MusicFile"][];
                        };
                    };
                };
                /** @description Song not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Song not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{songId}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lyrics for a song */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the song to retrieve lyrics for */
                    songId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of lyrics files for the song */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Raw lyrics text in LRC or LRCX format
                             * @example [02:00.082]＜最高速の別れの歌＞
                             *     [02:00.082][fu]<さい,1,2><こう,2,3><そく,3,4><わか,5,6><うた,8,9>
                             *     [02:00.082][dots]0,2,2,2,1,2,1,1,2,-1,0
                             *     [02:00.082][tags],119849/120111,120365/120813,121145/121376,121649,121906/122127,122242,122601,122851/123112,123153,
                             *     [02:00.082][tt]<0,1><515,2><1295,3><1799,4><2057,5><2393,6><2751,7><3001,8><3304,9>
                             *     [02:00.082][tr:en]<A farewell song at my highest speed>
                             *     [02:00.082][tr:zh]＜最高速的離別之歌＞
                             */
                            text: string;
                            parsed: components["schemas"]["LyricsKitLyrics"];
                        }[];
                    };
                };
                /** @description Song not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Song not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{songId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lyricova entries that reference a song */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination */
                    page?: number;
                };
                header?: never;
                path: {
                    /** @description ID of the song */
                    songId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of entries referencing the song */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Total number of entries for this song */
                            totalEntries?: number;
                            entries?: components["schemas"]["Entry"][];
                            song?: {
                                id?: components["schemas"]["Song"]["id"];
                                name?: components["schemas"]["Song"]["name"];
                            };
                            /** @description Current page number */
                            page?: number;
                            /** @description Total number of pages */
                            totalPages?: number;
                        };
                    };
                };
                /** @description Song not found or song has no entries */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: 404;
                            message: "Song not found";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tags with entry counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all tags with their entry counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Tag"] & {
                            /**
                             * @description Number of entries associated with this tag
                             * @example 42
                             */
                            entryCount?: number;
                        })[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tag by slug with its associated entries */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination */
                    page?: number;
                };
                header?: never;
                path: {
                    /** @description URL-friendly slug identifier of the tag */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tag details with paginated entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tag?: components["schemas"]["Tag"];
                            entries?: (components["schemas"]["Entry"] & {
                                verses?: components["schemas"]["Verse"][];
                                tags?: components["schemas"]["Tag"][];
                                pulses?: components["schemas"]["Pulse"][];
                            })[];
                            /** @description Total number of entries for this tag */
                            totalEntries?: number;
                            /** @description Current page number */
                            page?: number;
                            /** @description Total number of pages */
                            totalPages?: number;
                        };
                    };
                };
                /** @description Tag not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An album entry. */
        Album: {
            /**
             * Format: int64
             * @description VocaDB album ID for values greater than 0 or internal album ID otherwise.
             */
            id: number;
            /** @example 初音ミクの消失 Real and Repeat */
            name: string;
            /**
             * @description Sort order name
             * @example はつねみくのしょうしつ Real and Repeat
             */
            sortOrder: string;
            /** @description URL to the album’s cover image */
            coverUrl?: string | null;
            /** @description Full VocaDB or UtaiteDB API response */
            vocaDbJson?: components["schemas"]["AlbumForApiContract"];
            /** @description Whether this entry is an incomplete import from VocaDB/UtaiteDB */
            incomplete: boolean;
            /** @description UtaiteDB ID if from UtaiteDB */
            utaiteDbId?: number | null;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description An artist entry from VocaDB or UtaiteDB. */
        Artist: {
            /**
             * Format: int64
             * @description VocaDB artist ID for values greater than 0 or internal artist ID otherwise.
             */
            id: number;
            /** @example 初音ミク */
            name: string;
            /**
             * @description Sort order name
             * @example はつねみく
             */
            sortOrder: string;
            /** @description URL to the artist’s main picture */
            mainPictureUrl?: string | null;
            /**
             * @description Type of artist
             * @enum {string}
             */
            type: "Unknown" | "Circle" | "Label" | "Producer" | "Animator" | "Illustrator" | "Lyricist" | "Vocaloid" | "UTAU" | "CeVIO" | "OtherVoiceSynthesizer" | "OtherVocalist" | "OtherGroup" | "OtherIndividual" | "Utaite" | "Band" | "Vocalist" | "CoverArtist" | "SynthesizerV" | "Character" | "NEUTRINO" | "VoiSona" | "NewType" | "Voiceroid" | "Instrumentalist" | "Designer";
            /** @description ID of the base voice bank if this is a derived voice bank */
            baseVoiceBankId?: number | null;
            /** @description Full VocaDB or UtaiteDB API response */
            vocaDbJson?: components["schemas"]["ArtistForApiContract"];
            /** @description Whether this entry is incomplete and needs more data */
            incomplete: boolean;
            /** @description UtaiteDB ID if from UtaiteDB */
            utaiteDbId?: number | null;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description Junction table linking artists to albums with their roles. */
        ArtistOfAlbum: {
            /** Format: int64 */
            artistOfAlbumId: number;
            /** @description Roles specified for the artist */
            roles: ("Default" | "Animator" | "Arranger" | "Composer" | "Distributor" | "Illustrator" | "Instrumentalist" | "Lyricist" | "Mastering" | "Publisher" | "Vocalist" | "VoiceManipulator" | "Other" | "Mixer" | "Chorus" | "Encoder" | "VocalDataProvider")[];
            /** @description Effective roles after inheritance */
            effectiveRoles: ("Default" | "Animator" | "Arranger" | "Composer" | "Distributor" | "Illustrator" | "Instrumentalist" | "Lyricist" | "Mastering" | "Publisher" | "Vocalist" | "VoiceManipulator" | "Other" | "Mixer" | "Chorus" | "Encoder" | "VocalDataProvider")[];
            /**
             * @description Category of the artist in this album
             * @enum {string}
             */
            categories: "Nothing" | "Vocalist" | "Producer" | "Animator" | "Label" | "Circle" | "Other" | "Band" | "Illustrator" | "Subject";
            /** Format: int64 */
            albumId: number;
            /** Format: int64 */
            artistId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description Junction table linking artists to songs with their roles. */
        ArtistOfSong: {
            /** Format: int64 */
            artistOfSongId: number;
            /** @description VocaDB ID for this artist-song relationship */
            vocaDbId?: number | null;
            /** @description Roles the artist has in this song */
            artistRoles: ("Default" | "Animator" | "Arranger" | "Composer" | "Distributor" | "Illustrator" | "Instrumentalist" | "Lyricist" | "Mastering" | "Publisher" | "Vocalist" | "VoiceManipulator" | "Other" | "Mixer" | "Chorus" | "Encoder" | "VocalDataProvider")[];
            /** @description Categories of the artist in this song */
            categories: ("Nothing" | "Vocalist" | "Producer" | "Animator" | "Label" | "Circle" | "Other" | "Band" | "Illustrator" | "Subject")[];
            /** @description Custom name for the artist in this specific song */
            customName?: string | null;
            /** @description Whether this is a support/guest artist */
            isSupport: boolean;
            /** Format: int64 */
            songId: number;
            /** Format: int64 */
            artistId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description A Lyricova blog entry. */
        Entry: {
            /** Format: int64 */
            id?: number;
            /** @example 初音ミクの消失 -DEAD END- */
            title: string;
            /** @example cosMo@暴走P */
            producersName: string;
            /** @example 初音ミク */
            vocalistsName: string;
            /** Format: int64 */
            authorId: number;
            comment?: string | null;
            /** Format: date-time */
            recentActionDate?: string;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description Junction table linking music files to playlists with ordering. */
        FileInPlaylist: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description ID of the music file
             */
            fileId: number;
            /** @description Slug of the playlist */
            playlistId: string;
            /** @description Order of the file in the playlist */
            sortOrder: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description Mapping of Japanese words to segmented furigana (mono-ruby). */
        FuriganaMapping: {
            /**
             * @description Original Japanese text
             * @example 未来幻想
             */
            text: string;
            /**
             * @description Furigana pronunciation
             * @example みらいげんそう
             */
            furigana: string;
            /** @description Text segmented by morphemes */
            segmentedText?: string | null;
            /** @description Furigana segmented by morphemes */
            segmentedFurigana?: string | null;
        };
        /** @description A music file in the jukebox. */
        MusicFile: {
            /**
             * Format: int64
             * @description File ID in database
             */
            id: number;
            /**
             * @description Local path to the song file
             * @example shoshitsu/gekishou.mp3
             */
            path: string;
            /**
             * Format: int64
             * @description Size of file in bytes
             * @example 12345678
             */
            fileSize: number;
            /** @description ID of corresponding song in database */
            songId?: number | null;
            /** @description ID of corresponding album in database */
            albumId?: number | null;
            /** @description Name of the track stored in file */
            trackName?: string | null;
            /** @description Sort order key of name of the track */
            trackSortOrder?: string | null;
            /** @description Album of the track stored in file */
            albumName?: string | null;
            /** @description Sort order key of album */
            albumSortOrder?: string | null;
            /** @description Artist of the track stored in file */
            artistName?: string | null;
            /** @description Sort order key of artist */
            artistSortOrder?: string | null;
            /** @description If the file is accompanied with a lyrics file */
            hasLyrics: boolean;
            /** @description If the file has an embedded cover art */
            hasCover: boolean;
            /** @description If this entry needs review */
            needReview: boolean;
            /**
             * Format: float
             * @description Duration of the song in seconds
             * @example 301
             */
            duration: number;
            /**
             * @description MD5 hash of the file
             * @example 0123456789abcdef0123456789abcdef
             */
            hash: string;
            /** @description Number of times the file has been played */
            playCount: number;
            /** @description Date when the file was last played */
            lastPlayed?: string | null;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description A playlist of music files. */
        Playlist: {
            /**
             * @description URL-friendly identifier for the playlist
             * @example favorites
             */
            slug: string;
            /**
             * @description Display name of the playlist
             * @example My Favorites
             */
            name: string;
            /** @description Number of files in the playlist */
            readonly filesCount?: number;
        };
        /** @description A pulse on an entry. */
        Pulse: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description ID of the entry being pulsed
             */
            entryId: number;
            /**
             * Format: date-time
             * @description When the pulse was created
             */
            creationDate: string;
        };
        /** @description Key-value store for site metadata and configuration. */
        SiteMeta: {
            /**
             * @description Unique key for the metadata entry
             * @example site_title
             */
            key: string;
            /** @description Value stored for this key */
            value: string;
        };
        /** @description A song entry from VocaDB or UtaiteDB. */
        Song: {
            /**
             * Format: int64
             * @description VocaDB song ID for values greater than 0 or internal song ID otherwise.
             */
            id: number;
            /** @example 初音ミクの消失 -DEAD END- */
            name: string;
            /**
             * @description Sort order name
             * @example はつねみくのしょうしつ -DEAD END-
             */
            sortOrder: string;
            /** @description ID of the original song if this is a derived version */
            originalId?: number | null;
            /** @description Full VocaDB or UtaiteDB API response */
            vocaDbJson?: components["schemas"]["SongForApiContract"];
            /** @description UtaiteDB ID if from UtaiteDB */
            utaiteDbId?: number | null;
            /** @description URL to the song’s cover image */
            coverUrl?: string | null;
            /** @description Whether this entry is incomplete and needs more data */
            incomplete: boolean;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description Junction table linking songs to albums with track information. */
        SongInAlbum: {
            /** Format: int64 */
            songInAlbumId: number;
            /** @description VocaDB ID for this song-album relationship */
            vocaDbId?: number | null;
            /** @description Disk/disc number in multi-disc albums */
            diskNumber?: number | null;
            /** @description Track number on the disc */
            trackNumber?: number | null;
            /** @description Name of the song as it appears on the album */
            name?: string | null;
            /** Format: int64 */
            songId: number;
            /** Format: int64 */
            albumId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description Junction table linking songs to lyricova entries. */
        SongOfEntry: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description ID of the song
             */
            songId: number;
            /**
             * Format: int64
             * @description ID of the entry
             */
            entryId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description A tag for categorizing entries. */
        Tag: {
            /**
             * @description URL-friendly identifier for the tag
             * @example core
             */
            slug: string;
            /**
             * @description Display name of the tag
             * @example Core
             */
            name: string;
            /**
             * @description Hex color code for the tag
             * @example #39c5bb
             */
            color: string;
        };
        /** @description Junction table linking tags to entries. */
        TagOfEntry: {
            /** Format: int64 */
            id: number;
            /** @description Slug of the tag */
            tagId: string;
            /**
             * Format: int64
             * @description ID of the entry
             */
            entryId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description A user account in the system. */
        User: {
            /** Format: int64 */
            id: number;
            /**
             * @description Unique username for login
             * @example admin
             */
            username: string;
            /**
             * @description Display name shown to other users
             * @example Administrator
             */
            displayName: string;
            /**
             * Format: email
             * @description Unique email address
             * @example admin@example.com
             */
            email: string;
            /** @description MD5 hash of email (for Gravatar) */
            readonly emailMD5?: string;
            /**
             * @description User role determining permissions
             * @enum {string}
             */
            role: "admin" | "guest";
            /** @description OAuth provider name if using OAuth */
            provider?: string;
            /** @description OAuth provider’s user ID */
            provider_id?: string;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description WebAuthn public key credential for passwordless authentication. */
        UserPublicKeyCredential: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description ID of the user who owns this credential
             */
            userId: number;
            /** @description External credential ID from WebAuthn */
            externalId: string;
            /** @description Public key for the credential (base64 encoded) */
            publicKey: string;
            /** @description Optional remarks or nickname for this credential */
            remarks?: string | null;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
        };
        /** @description A verse or translation of lyrics for an entry. */
        Verse: {
            /** Format: int64 */
            id: number;
            /**
             * @description Language code of the verse
             * @example ja
             */
            language: string;
            /** @description Whether this is the original language version */
            isOriginal: boolean;
            /** @description Whether this is the main verse to display */
            isMain: boolean;
            /**
             * @description Plain text content of the verse
             * @example 「信じたものは、
             *     都合のいい妄想を
             *     繰り返し映し出す鏡。」
             */
            text: string;
            /**
             * @description HTML-formatted content of the verse
             * @example 「<ruby><rb>信</rb><rt>しん</rt></ruby>じたものは、<br>
             *     　<ruby><rb>都</rb><rt>つ</rt></ruby><ruby><rb>合</rb><rt>ごう</rt></ruby>のいい<ruby><rb>妄</rb><rt>もう</rt></ruby><ruby><rb>想</rb><rt>そう</rt></ruby>を<br>
             *     　<ruby><rb>繰</rb><rt>く</rt></ruby>り<ruby><rb>返</rb><rt>かえ</rt></ruby>し<rb>映</rb><rt>うつ</rt></ruby>し<ruby><rb>出</rb><rt>だ</rt></ruby>す<ruby><rb>鏡</rb><rt>かがみ</rt></ruby>。」
             */
            html?: string | null;
            /**
             * @description Stylized text with special formatting
             * @example 「信じたものは、
             *     　都合のいい妄想を
             *     　繰り返し映し出す鏡。」
             */
            stylizedText?: string | null;
            /** @description Name of the translator */
            translator?: string | null;
            /**
             * @description Sequence for typing animation
             * @example [
             *       [
             *         [
             *           "「信じた",
             *           "『しんじた"
             *         ],
             *         [
             *           "ものは、",
             *           "ものは、"
             *         ]
             *       ],
             *       [
             *         [
             *           "都合の",
             *           "つごうの"
             *         ],
             *         [
             *           "いい",
             *           "いい"
             *         ],
             *         [
             *           "妄想を",
             *           "もうそうを"
             *         ]
             *       ],
             *       [
             *         [
             *           "繰り返し",
             *           "くりかえし"
             *         ],
             *         [
             *           "映し出す",
             *           "うつしだす"
             *         ],
             *         [
             *           "鏡。」",
             *           "かがみ。」"
             *         ]
             *       ]
             *     ]
             */
            typingSequence: string[][][];
            /**
             * Format: int64
             * @description ID of the associated entry
             */
            entryId: number;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description A video file associated with a song. */
        VideoFile: {
            /** Format: int64 */
            id: number;
            /** @description Local path to the video file */
            path: string;
            /**
             * Format: int64
             * @description ID of the associated song
             */
            songId: number;
            /** @description Title of the video */
            title: string;
            /** @description Original URL of the video source */
            sourceUrl?: string | null;
            /**
             * @description Type of video content
             * @enum {string}
             */
            type: "Original" | "PV" | "Derived" | "Subtitled" | "OnVocal" | "OffVocal" | "Other";
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            updatedOn?: string;
            deletionDate?: string | null;
        };
        /** @description Furigana/romaji to words in a lyrics line. */
        LyricsKitRangeAttachment: {
            /**
             * @description Furigana/romaji content
             * @example さい
             */
            content: string;
            /**
             * @description Starting character per Extended Grapheme Cluster (including)
             * @example 1
             */
            leftIndex: number;
            /**
             * @description Ending character per Extended Grapheme Cluster (excluding)
             * @example 2
             */
            rightIndex: number;
        };
        /** @description Time tag per word to a lyrics line. */
        LyricsKitWordTimeTag: {
            /**
             * Format: float
             * @description Time when the time tag happens, in seconds.
             * @example 0.515
             */
            timeTag: number;
            /**
             * @description Starting character per Extended Grapheme Cluster of this tag
             * @example 1
             */
            index: number;
        };
        /** @description Time tag per word to a lyrics line. */
        LyricsKitWordTimeAttachment: {
            /** @description Duration of line in seconds. */
            duration?: number | null;
            /**
             * @description Tags in the line.
             * @example [
             *       {
             *         "timeTag": 0,
             *         "index": 1
             *       },
             *       {
             *         "timeTag": 0.515,
             *         "index": 2
             *       },
             *       {
             *         "timeTag": 1.295,
             *         "index": 3
             *       },
             *       {
             *         "timeTag": 1.799,
             *         "index": 4
             *       },
             *       {
             *         "timeTag": 2.057,
             *         "index": 5
             *       },
             *       {
             *         "timeTag": 2.393,
             *         "index": 6
             *       },
             *       {
             *         "timeTag": 2.751,
             *         "index": 7
             *       },
             *       {
             *         "timeTag": 3.001,
             *         "index": 8
             *       },
             *       {
             *         "timeTag": 3.304,
             *         "index": 9
             *       }
             *     ]
             */
            tags: components["schemas"]["LyricsKitWordTimeTag"][] | null;
        };
        /** @description Attachments to a lyrics line. */
        LyricsKitAttachment: {
            timeTag?: components["schemas"]["LyricsKitWordTimeAttachment"] | null;
            /**
             * @description Translation of unspecified language
             * @example null
             */
            translation?: string | null;
            /**
             * @description Translation by language code
             * @example {
             *       "en": "<A farewell song at my highest speed>",
             *       "zh": "＜最高速的離別之歌＞"
             *     }
             */
            translations: {
                [key: string]: string;
            };
            /**
             * @example [
             *       {
             *         "content": "さい",
             *         "leftIndex": 1,
             *         "rightIndex": 2
             *       },
             *       {
             *         "content": "こう",
             *         "leftIndex": 2,
             *         "rightIndex": 3
             *       },
             *       {
             *         "content": "そく",
             *         "leftIndex": 3,
             *         "rightIndex": 4
             *       },
             *       {
             *         "content": "わか",
             *         "leftIndex": 5,
             *         "rightIndex": 6
             *       },
             *       {
             *         "content": "うた",
             *         "leftIndex": 8,
             *         "rightIndex": 9
             *       }
             *     ]
             */
            furigana?: components["schemas"]["LyricsKitRangeAttachment"][] | null;
            /** @example null */
            romaji?: components["schemas"]["LyricsKitRangeAttachment"][] | null;
            /** @description Role of the line */
            role: number;
            /** @description Whether this line is minor (e.g., backing vocals) */
            minor: boolean;
        };
        /** @description A line of parsed lyrics. */
        LyricsKitLyricsLine: {
            /**
             * @description The text content of the lyrics line
             * @example ＜最高速の別れの歌＞
             */
            content: string;
            /**
             * Format: float
             * @description Offset of the line in seconds
             * @example 120.082
             */
            position: number;
            attachments: components["schemas"]["LyricsKitAttachment"];
        };
        /** @description Parsed lyrics. */
        LyricsKitLyrics: {
            /** @description Quality rating of the lyrics */
            quality?: number | null;
            /** @description Array of lyrics lines */
            lines: components["schemas"]["LyricsKitLyricsLine"][];
            /** @description Duration of the lyrics in seconds. */
            length?: number | null;
            /** @description Available translation language codes */
            translationLanguages: string[];
        };
        /** @enum {string} */
        ArtistType: "Unknown" | "Circle" | "Label" | "Producer" | "Animator" | "Illustrator" | "Lyricist" | "Vocaloid" | "UTAU" | "CeVIO" | "OtherVoiceSynthesizer" | "OtherVocalist" | "OtherGroup" | "OtherIndividual" | "Utaite" | "Band" | "Vocalist" | "Character" | "SynthesizerV" | "CoverArtist" | "NEUTRINO" | "VoiSona" | "NewType" | "Voiceroid" | "Instrumentalist" | "Designer" | "VOICEVOX" | "ACEVirtualSinger" | "AIVOICE";
        /** @enum {string} */
        EntryStatus: "Draft" | "Finished" | "Approved" | "Locked";
        ArtistContract: {
            additionalNames?: string | null;
            artistType?: components["schemas"]["ArtistType"];
            deleted?: boolean;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            pictureMime?: string | null;
            /** Format: date-time */
            releaseDate?: string | null;
            status?: components["schemas"]["EntryStatus"];
            /** Format: int32 */
            version?: number;
        };
        /** @enum {string} */
        ArtistLinkType: "CharacterDesigner" | "Group" | "Illustrator" | "Manager" | "VoiceProvider";
        ArtistForArtistForApiContract: {
            artist?: components["schemas"]["ArtistContract"];
            linkType?: components["schemas"]["ArtistLinkType"];
        };
        /** @enum {string} */
        ContentLanguageSelection: "Unspecified" | "Japanese" | "Romaji" | "English";
        EntryThumbForApiContract: {
            mime?: string | null;
            name?: string | null;
            urlOriginal?: string | null;
            urlSmallThumb?: string | null;
            urlThumb?: string | null;
            urlTinyThumb?: string | null;
        };
        LocalizedStringContract: {
            language?: components["schemas"]["ContentLanguageSelection"];
            value?: string | null;
        };
        /** @enum {string} */
        ArtistCategories: "Nothing" | "Vocalist" | "Producer" | "Animator" | "Label" | "Circle" | "Other" | "Band" | "Illustrator" | "Subject";
        /** @enum {string} */
        ArtistRoles: "Default" | "Animator" | "Arranger" | "Composer" | "Distributor" | "Illustrator" | "Instrumentalist" | "Lyricist" | "Mastering" | "Publisher" | "Vocalist" | "VoiceManipulator" | "Other" | "Mixer" | "Chorus" | "Encoder" | "VocalDataProvider" | "RecordingEngineer";
        ArtistForAlbumForApiContract: {
            artist?: components["schemas"]["ArtistContract"];
            categories?: components["schemas"]["ArtistCategories"];
            effectiveRoles?: components["schemas"]["ArtistRoles"];
            isSupport?: boolean;
            name?: string | null;
            roles?: components["schemas"]["ArtistRoles"];
        };
        /** @enum {string} */
        DiscMediaType: "Audio" | "Video";
        AlbumDiscPropertiesContract: {
            /** Format: int32 */
            discNumber?: number;
            /** Format: int32 */
            id?: number;
            mediaType?: components["schemas"]["DiscMediaType"];
            name?: string | null;
        };
        /** @enum {string} */
        DiscType: "Unknown" | "Album" | "Single" | "EP" | "SplitAlbum" | "Compilation" | "Video" | "Artbook" | "Game" | "Fanmade" | "Instrumental" | "Other" | "Drama";
        AlbumIdentifierContract: {
            value?: string | null;
        };
        PVExtendedMetadata: {
            json?: string | null;
        };
        /** @enum {string} */
        PVService: "NicoNicoDouga" | "Youtube" | "SoundCloud" | "Vimeo" | "Piapro" | "Bilibili" | "File" | "LocalFile" | "Creofuga" | "Bandcamp";
        /** @enum {string} */
        PVType: "Original" | "Reprint" | "Other";
        PVContract: {
            author?: string | null;
            /** Format: int32 */
            createdBy?: number | null;
            description?: string | null;
            disabled?: boolean;
            extendedMetadata?: components["schemas"]["PVExtendedMetadata"];
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            length?: number;
            name?: string | null;
            /** Format: date-time */
            publishDate?: string | null;
            pvId?: string | null;
            service?: components["schemas"]["PVService"];
            pvType?: components["schemas"]["PVType"];
            thumbUrl?: string | null;
            url?: string | null;
        };
        OptionalDateTimeContract: {
            /** Format: int32 */
            day?: number | null;
            isEmpty?: boolean;
            /** Format: int32 */
            month?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        /** @enum {string} */
        ArtistEventRoles: "Default" | "Dancer" | "DJ" | "Instrumentalist" | "Organizer" | "Promoter" | "VJ" | "Vocalist" | "VoiceManipulator" | "OtherPerformer" | "Other";
        ArtistForEventContract: {
            artist?: components["schemas"]["ArtistContract"];
            effectiveRoles?: components["schemas"]["ArtistEventRoles"];
            /** Format: int32 */
            id?: number;
            name?: string | null;
            roles?: components["schemas"]["ArtistEventRoles"];
        };
        /** @enum {string} */
        EventCategory: "Unspecified" | "AlbumRelease" | "Anniversary" | "Club" | "Concert" | "Contest" | "Convention" | "Other" | "Festival";
        /** @enum {string} */
        WebLinkCategory: "Official" | "Commercial" | "Reference" | "Other";
        WebLinkContract: {
            category?: components["schemas"]["WebLinkCategory"];
            description?: string | null;
            descriptionOrUrl?: string | null;
            disabled?: boolean;
            /** Format: int32 */
            id?: number;
            url?: string | null;
        };
        ReleaseEventSeriesContract: {
            additionalNames?: string | null;
            category?: components["schemas"]["EventCategory"];
            deleted?: boolean;
            description?: string | null;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            pictureMime?: string | null;
            status?: components["schemas"]["EntryStatus"];
            urlSlug?: string | null;
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkContract"][] | null;
        };
        /** @enum {string} */
        SongListFeaturedCategory: "Nothing" | "Concerts" | "VocaloidRanking" | "Pools" | "Other";
        SongListBaseContract: {
            featuredCategory?: components["schemas"]["SongListFeaturedCategory"];
            /** Format: int32 */
            id?: number;
            name?: string | null;
        };
        TagBaseContract: {
            additionalNames?: string | null;
            categoryName?: string | null;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            urlSlug?: string | null;
        };
        TagUsageForApiContract: {
            /** Format: int32 */
            count?: number;
            tag?: components["schemas"]["TagBaseContract"];
        };
        OptionalGeoPointContract: {
            formatted?: string | null;
            hasValue?: boolean;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        VenueContract: {
            additionalNames?: string | null;
            address?: string | null;
            addressCountryCode?: string | null;
            coordinates?: components["schemas"]["OptionalGeoPointContract"];
            deleted?: boolean;
            description?: string | null;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            status?: components["schemas"]["EntryStatus"];
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkContract"][] | null;
        };
        ReleaseEventContract: {
            additionalNames?: string | null;
            category?: components["schemas"]["EventCategory"];
            customName?: boolean;
            /** Format: date-time */
            date?: string | null;
            deleted?: boolean;
            description?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            readonly hasVenueOrVenueName?: boolean;
            /** Format: int32 */
            id?: number;
            inheritedCategory?: components["schemas"]["EventCategory"];
            name?: string | null;
            pictureMime?: string | null;
            series?: components["schemas"]["ReleaseEventSeriesContract"];
            songList?: components["schemas"]["SongListBaseContract"];
            status?: components["schemas"]["EntryStatus"];
            urlSlug?: string | null;
            venue?: components["schemas"]["VenueContract"];
            venueName?: string | null;
            /** Format: int32 */
            version?: number;
        };
        WebLinkForApiContract: {
            category?: components["schemas"]["WebLinkCategory"];
            description?: string | null;
            descriptionOrUrl?: string | null;
            disabled?: boolean;
            /** Format: int32 */
            id?: number;
            url?: string | null;
        };
        VenueForApiContract: {
            additionalNames?: string | null;
            address?: string | null;
            addressCountryCode?: string | null;
            coordinates?: components["schemas"]["OptionalGeoPointContract"];
            deleted?: boolean;
            description?: string | null;
            events?: components["schemas"]["ReleaseEventContract"][] | null;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            names?: components["schemas"]["LocalizedStringContract"][] | null;
            status?: components["schemas"]["EntryStatus"];
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkForApiContract"][] | null;
        };
        ReleaseEventForApiContract: {
            additionalNames?: string | null;
            artists?: components["schemas"]["ArtistForEventContract"][] | null;
            category?: components["schemas"]["EventCategory"];
            /** Format: date-time */
            date?: string | null;
            description?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            /** Format: int32 */
            id?: number;
            mainPicture?: components["schemas"]["EntryThumbForApiContract"];
            name?: string | null;
            names?: components["schemas"]["LocalizedStringContract"][] | null;
            pvs?: components["schemas"]["PVContract"][] | null;
            series?: components["schemas"]["ReleaseEventSeriesContract"];
            /** Format: int32 */
            seriesId?: number | null;
            /** Format: int32 */
            seriesNumber?: number;
            seriesSuffix?: string | null;
            songList?: components["schemas"]["SongListBaseContract"];
            status?: components["schemas"]["EntryStatus"];
            tags?: components["schemas"]["TagUsageForApiContract"][] | null;
            urlSlug?: string | null;
            venue?: components["schemas"]["VenueForApiContract"];
            venueName?: string | null;
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkForApiContract"][] | null;
        };
        /** @enum {string} */
        SongVoteRating: "Nothing" | "Dislike" | "Like" | "Favorite";
        AlbumContract: {
            additionalNames?: string | null;
            artistString?: string | null;
            coverPictureMime?: string | null;
            /** Format: date-time */
            createDate?: string;
            deleted?: boolean;
            discType?: components["schemas"]["DiscType"];
            /** Format: int32 */
            id?: number;
            name?: string | null;
            /** Format: double */
            ratingAverage?: number;
            /** Format: int32 */
            ratingCount?: number;
            releaseDate?: components["schemas"]["OptionalDateTimeContract"];
            releaseEvent?: components["schemas"]["ReleaseEventForApiContract"];
            status?: components["schemas"]["EntryStatus"];
            /** Format: int32 */
            version?: number;
        };
        ArtistForSongContract: {
            artist?: components["schemas"]["ArtistContract"];
            categories?: components["schemas"]["ArtistCategories"];
            effectiveRoles?: components["schemas"]["ArtistRoles"];
            /** Format: int32 */
            id?: number;
            isCustomName?: boolean;
            isSupport?: boolean;
            name?: string | null;
            roles?: components["schemas"]["ArtistRoles"];
        };
        /** @enum {string} */
        TranslationType: "Original" | "Romanized" | "Translation";
        LyricsForSongContract: {
            cultureCodes?: string[] | null;
            /** Format: int32 */
            id?: number;
            /** @default  */
            source: string | null;
            translationType?: components["schemas"]["TranslationType"];
            /** @default  */
            url: string | null;
            value?: string | null;
        };
        /** @enum {string} */
        PVServices: "Nothing" | "NicoNicoDouga" | "Youtube" | "SoundCloud" | "Vimeo" | "Piapro" | "Bilibili" | "File" | "LocalFile" | "Creofuga" | "Bandcamp";
        /** @enum {string} */
        SongType: "Unspecified" | "Original" | "Remaster" | "Remix" | "Cover" | "Arrangement" | "Instrumental" | "Mashup" | "MusicPV" | "DramaPV" | "Live" | "Illustration" | "Other" | "Rearrangement" | "ShortVersion";
        SongForApiContract: {
            additionalNames?: string | null;
            albums?: components["schemas"]["AlbumContract"][] | null;
            artists?: components["schemas"]["ArtistForSongContract"][] | null;
            artistString?: string | null;
            /** Format: date-time */
            createDate?: string;
            defaultName?: string | null;
            defaultNameLanguage?: components["schemas"]["ContentLanguageSelection"];
            deleted?: boolean;
            /** Format: int32 */
            favoritedTimes?: number;
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            lengthSeconds?: number;
            lyrics?: components["schemas"]["LyricsForSongContract"][] | null;
            mainPicture?: components["schemas"]["EntryThumbForApiContract"];
            /** Format: int32 */
            maxMilliBpm?: number | null;
            /** Format: int32 */
            mergedTo?: number;
            /** Format: int32 */
            minMilliBpm?: number | null;
            name?: string | null;
            names?: components["schemas"]["LocalizedStringContract"][] | null;
            /** Format: int32 */
            originalVersionId?: number;
            /** Format: date-time */
            publishDate?: string | null;
            pvs?: components["schemas"]["PVContract"][] | null;
            pvServices?: components["schemas"]["PVServices"];
            /** Format: int32 */
            ratingScore?: number;
            releaseEvent?: components["schemas"]["ReleaseEventForApiContract"];
            releaseEvents?: components["schemas"]["ReleaseEventForApiContract"][] | null;
            songType?: components["schemas"]["SongType"];
            status?: components["schemas"]["EntryStatus"];
            tags?: components["schemas"]["TagUsageForApiContract"][] | null;
            thumbUrl?: string | null;
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkForApiContract"][] | null;
            cultureCodes?: string[] | null;
        };
        SongInAlbumForApiContract: {
            /** Format: int32 */
            discNumber?: number;
            /** Format: int32 */
            id?: number;
            name?: string | null;
            rating?: components["schemas"]["SongVoteRating"];
            song?: components["schemas"]["SongForApiContract"];
            /** Format: int32 */
            trackNumber?: number;
            computedCultureCodes?: string[] | null;
        };
        AlbumForApiContract: {
            additionalNames?: string | null;
            artists?: components["schemas"]["ArtistForAlbumForApiContract"][] | null;
            artistString?: string | null;
            barcode?: string | null;
            catalogNumber?: string | null;
            /** Format: date-time */
            createDate?: string;
            defaultName?: string | null;
            defaultNameLanguage?: components["schemas"]["ContentLanguageSelection"];
            deleted?: boolean;
            description?: string | null;
            discs?: components["schemas"]["AlbumDiscPropertiesContract"][] | null;
            discType?: components["schemas"]["DiscType"];
            /** Format: int32 */
            id?: number;
            identifiers?: components["schemas"]["AlbumIdentifierContract"][] | null;
            mainPicture?: components["schemas"]["EntryThumbForApiContract"];
            /** Format: int32 */
            mergedTo?: number;
            name?: string | null;
            names?: components["schemas"]["LocalizedStringContract"][] | null;
            pvs?: components["schemas"]["PVContract"][] | null;
            /** Format: double */
            ratingAverage?: number;
            /** Format: int32 */
            ratingCount?: number;
            releaseDate?: components["schemas"]["OptionalDateTimeContract"];
            releaseEvent?: components["schemas"]["ReleaseEventForApiContract"];
            releaseEvents?: components["schemas"]["ReleaseEventForApiContract"][] | null;
            status?: components["schemas"]["EntryStatus"];
            tags?: components["schemas"]["TagUsageForApiContract"][] | null;
            tracks?: components["schemas"]["SongInAlbumForApiContract"][] | null;
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkForApiContract"][] | null;
        };
        ArtistRelationsForApi: {
            latestAlbums?: components["schemas"]["AlbumForApiContract"][] | null;
            latestEvents?: components["schemas"]["ReleaseEventForApiContract"][] | null;
            latestSongs?: components["schemas"]["SongForApiContract"][] | null;
            popularAlbums?: components["schemas"]["AlbumForApiContract"][] | null;
            popularSongs?: components["schemas"]["SongForApiContract"][] | null;
        };
        ArtistForApiContract: {
            additionalNames?: string | null;
            artistLinks?: components["schemas"]["ArtistForArtistForApiContract"][] | null;
            artistLinksReverse?: components["schemas"]["ArtistForArtistForApiContract"][] | null;
            artistType?: components["schemas"]["ArtistType"];
            baseVoicebank?: components["schemas"]["ArtistContract"];
            /** Format: date-time */
            createDate?: string;
            defaultName?: string | null;
            defaultNameLanguage?: components["schemas"]["ContentLanguageSelection"];
            deleted?: boolean;
            description?: string | null;
            /** Format: int32 */
            id?: number;
            mainPicture?: components["schemas"]["EntryThumbForApiContract"];
            /** Format: int32 */
            mergedTo?: number;
            name?: string | null;
            names?: components["schemas"]["LocalizedStringContract"][] | null;
            pictureMime?: string | null;
            relations?: components["schemas"]["ArtistRelationsForApi"];
            /** Format: date-time */
            releaseDate?: string | null;
            status?: components["schemas"]["EntryStatus"];
            tags?: components["schemas"]["TagUsageForApiContract"][] | null;
            /** Format: int32 */
            version?: number;
            webLinks?: components["schemas"]["WebLinkForApiContract"][] | null;
        };
    };
    responses: {
        /** @description Unauthorized access */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": "Unauthorized";
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
